---
sidebar: sidebar 
permalink: ontap991fo_technical_resources.html 
keywords:  
summary:  
---
= Ressources techniques
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


Cette section couvre les ressources techniques disponibles qui décrivent en détail les fonctions mentionnées dans ce document.



== Rapports techniques

* Tr-4067 : Guide des meilleures pratiques et de l'implémentation de NetApp ONTAP pour NFS
+
https://www.netapp.com/us/media/tr-4067.pdf["https://www.netapp.com/us/media/tr-4067.pdf"^]

* Tr-4515 : systèmes avec baie SAN 100 % ONTAP AFF
+
https://www.netapp.com/pdf.html?item=/media/10379-tr4515pdf.pdf["https://www.netapp.com/pdf.html?item=/media/10379-tr4515pdf.pdf"^]

* Tr-4526 : stockage WORM conforme avec NetApp SnapLock
+
https://www.netapp.com/pdf.html?item=/media/6158-tr4526pdf.pdf["https://www.netapp.com/pdf.html?item=/media/6158-tr4526pdf.pdf"^]

* Tr-4569 : guide de renforcement de la sécurité de la solution ONTAP 9
+
https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf["https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf"^]

* Tr-4571 : bonnes pratiques pour NetApp FlexGroup volumes
+
https://www.netapp.com/us/media/tr-4571.pdf["https://www.netapp.com/us/media/tr-4571.pdf"^]

* Tr-4597 : VMware vSphere avec ONTAP
+
https://www.netapp.com/us/media/tr-4597.pdf["https://www.netapp.com/us/media/tr-4597.pdf"^]

* Tr-4598 : meilleures pratiques de FabricPool
+
https://www.netapp.com/us/media/tr-4598.pdf["https://www.netapp.com/us/media/tr-4598.pdf"^]

* Tr-4684 : implémentation et configuration des SAN modernes avec NVMe/FC
+
https://www.netapp.com/pdf.html?item=/media/10681-tr4684.pdf["https://www.netapp.com/pdf.html?item=/media/10681-tr4684.pdf"^]

* Tr-4678 : protection et sauvegarde des données - FlexGroup volumes
+
https://www.netapp.com/us/media/tr-4678.pdf["https://www.netapp.com/us/media/tr-4678.pdf"^]

* Tr-4689 : architecture et conception de la solution IP de MetroCluster
+
https://www.netapp.com/us/media/tr-4689.pdf["https://www.netapp.com/us/media/tr-4689.pdf"^]

* Tr-4705 : architecture et conception de la solution NetApp MetroCluster
+
https://www.netapp.com/pdf.html?item=/media/13480-tr4705pdf.pdf["https://www.netapp.com/pdf.html?item=/media/13480-tr4705pdf.pdf"^]

* Tr-4743 : FlexCache dans ONTAP
+
https://www.netapp.com/pdf.html?item=/media/7336-tr4743pdf.pdf["https://www.netapp.com/pdf.html?item=/media/7336-tr4743pdf.pdf"^]

* Tr-4814 : rapport S3 dans les meilleures pratiques de ONTAP
+
https://www.netapp.com/pdf.html?item=/media/17219-tr4814pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17219-tr4814pdf.pdf"^]





== Podcasts

* Épisode 288 du podcast Tech OnTap : ONTAP System Manager 9.9.1
+
https://soundcloud.com/techontap_podcast/episode-288-ontap-system-manager-991["https://soundcloud.com/techontap_podcast/episode-288-ontap-system-manager-991"^]


